Dev
Kate0704/PPO pull request #1
Opened 2020-12-04 16:47 UTC by Kate0704

Pull request for **Converter lab**.
Zhevniak Katerina 853502

2020-12-07 15:26 UTC, gmltA requested changes
Kate, can you put all your code for your first project into one PR? Now you have some of it already in master branch.

2020-12-07 15:59 UTC, Kate0704 commented
@gmltA 
May I just delete master branch, create a new branch and then create a new PR??

2020-12-07 16:46 UTC, Kate0704 commented
Master branch is empty now.

2020-12-09 16:06 UTC, gmltA approved these changes

2020-12-14 06:49 UTC, merged